/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DeleteModal: typeof import('./src/components/layout/DeleteModal.vue')['default']
    FormButtons: typeof import('./src/components/layout/FormButtons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ResourceForm: typeof import('./src/components/ResourceForm.vue')['default']
    ResourceModal: typeof import('./src/components/layout/ResourceModal.vue')['default']
    ResourceTable: typeof import('./src/components/tables/ResourceTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
